# MediaWiki with MariaDB and fuseki
#
# Access via "http://localhost:8080"
version: '3'
services:
  database:
    image: ikcap/disk_database
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
  mediawiki:
    image: ikcap/disk_wiki
    build:
      context: ./wiki/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
    links:
      - database
      #- fuseki
    #volumes:
      #- /var/www/html/images
#  fuseki:
#    image: stain/jena-fuseki
#    restart: always
