name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

env:
  IMAGE_NAME_DATABASE: ods-database
  IMAGE_NAME_WIKI: ods-wiki

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      packages: write

    runs-on: ubuntu-latest
    #runs-on: "ubuntu-18.04"

    steps:
    - uses: actions/checkout@v2

    - name: Build wiki image
      run: |
        docker build  ./wiki   --tag ${IMAGE_NAME_WIKI}
    
    - name: Build database image
      run: |
        docker build ./database --tag ${IMAGE_NAME_DATABASE}
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
      with:
        image-ref: ods-wiki 
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
        exit-code: '1'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: always() 
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Push database image
      run: |
        IMAGE_DATABASE_ID=ikcap/disk_database
        IMAGE_DATABASE_ID=$(echo $IMAGE_DATABASE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_DATABASE $IMAGE_DATABASE_ID:$VERSION
        docker push $IMAGE_DATABASE_ID:$VERSION
        docker tag $IMAGE_NAME_DATABASE $IMAGE_DATABASE_ID:$GITHUB_SHA
        docker push $IMAGE_DATABASE_ID:$GITHUB_SHA

    - name: Push wiki image
      run: |
        IMAGE_WIKI_ID=ikcap/disk_wiki
        IMAGE_WIKI_ID=$(echo $IMAGE_WIKI_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_WIKI $IMAGE_WIKI_ID:$VERSION
        docker push $IMAGE_WIKI_ID:$VERSION
        docker tag $IMAGE_NAME_WIKI $IMAGE_WIKI_ID:$GITHUB_SHA
        docker push $IMAGE_WIKI_ID:$GITHUB_SHA
