name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

env:
  IMAGE_NAME_DATABASE: ods-database
  IMAGE_NAME_WIKI: ods-wiki

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Build wiki image
      run: |
        docker build  ./wiki   --tag ${IMAGE_NAME_WIKI}
    
    - name: Build database image
      run: |
        docker build ./database --tag ${IMAGE_NAME_DATABASE}
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Push database image
      run: |
        IMAGE_DATABASE_ID=ikcap/disk_database
        IMAGE_DATABASE_ID=$(echo $IMAGE_DATABASE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_DATABASE $IMAGE_DATABASE_ID:$VERSION
        docker push $IMAGE_DATABASE_ID:$VERSION
        docker tag $IMAGE_NAME_DATABASE $IMAGE_DATABASE_ID:$GITHUB_SHA
        docker push $IMAGE_DATABASE_ID:$GITHUB_SHA

    - name: Push wiki image
      run: |
        IMAGE_WIKI_ID=ikcap/disk_wiki
        IMAGE_WIKI_ID=$(echo $IMAGE_WIKI_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "master" ] && VERSION=latest
        docker tag $IMAGE_NAME_WIKI $IMAGE_WIKI_ID:$VERSION
        docker push $IMAGE_WIKI_ID:$VERSION
        docker tag $IMAGE_NAME_WIKI $IMAGE_WIKI_ID:$GITHUB_SHA
        docker push $IMAGE_WIKI_ID:$GITHUB_SHA